openapi: 3.0.0
info:
  title: 'CRUD de Usuários'
  version: '0.1'
servers:
  -
    url: 'http://localhost:8000'
    description: 'Servidor Local'
paths:
  /api/users:
    get:
      tags:
        - Usuários
      summary: 'Lista todos os usuários com paginação'
      operationId: getUsersList
      responses:
        '200':
          description: 'Lista de usuários retornada com sucesso'
tags:
  -
    name: Usuários
    description: Usuários
